# Generated by Django 3.1.4 on 2021-02-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exercise_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('Strength Training', 'Strength Training'), (
                'Cardio', 'Cardio'), ('Stretching', 'Stretching')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routine',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
