# Generated by Django 3.1.4 on 2021-03-01 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210206_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 1, 12, 28, 19, 186582, tzinfo=utc), null=True),
        ),
    ]
